import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>NextJS Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center mt-12">
        <h1>
          Welcome to the NextJS Boilerplate
        </h1>
        <p>
          Checkout the README.md for more details on how to get started!
        </p>
      </main>
    </>
  );
}
